// Genre actions
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';
export const GENRE_IS_LOADING = 'GENRE_IS_LOADING';

// Movie actions
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const STORE_MOVIE = 'STORE_MOVIE';
export const MOVIE_IS_LOADING = 'MOVIE_IS_LOADING';

// Category action
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const NOW_PLAYING_MOVIES_IS_LOADING = 'NOW_PLAYING_MOVIES_IS_LOADING';
export const POPULAR_MOVIES_IS_LOADING = 'POPULAR_MOVIES_IS_LOADING';
// export const SHOW_CATEGORY_IS_LOADING = 'SHOW_CATEGORY_IS_LOADING';
