// Movie actions
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const STORE_MOVIE = 'STORE_MOVIE';
export const MOVIE_IS_LOADING = 'MOVIE_IS_LOADING';

// Show actions
export const FETCH_SHOW = 'FETCH_SHOW';
export const STORE_SHOW = 'STORE_SHOW';
export const SHOW_IS_LOADING = 'SHOW_IS_LOADING';

// Category action
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const NOW_PLAYING_MOVIES_IS_LOADING = 'NOW_PLAYING_MOVIES_IS_LOADING';
export const POPULAR_MOVIES_IS_LOADING = 'POPULAR_MOVIES_IS_LOADING';
export const FETCH_ON_THE_AIR_SHOWS = 'FETCH_ON_THE_AIR_SHOWS';
export const ON_THE_AIR_SHOWS_IS_LOADING = 'ON_THE_AIR_SHOWS_IS_LOADING';

// Discover action
export const FETCH_DISCOVER_MOVIES = 'FETCH_DISCOVER_MOVIES';
export const FETCH_DISCOVER_SHOWS = "FETCH_DISCOVER_SHOWS";
export const DISCOVER_MOVIES_IS_LOADING = "DISCOVER_MOVIES_IS_LOADING";
export const DISCOVER_SHOWS_IS_LOADING = "DISCOVER_SHOWS_IS_LOADING";
